### ISSUE TITLE
Stopped working today

### ISSUE THREAD

**Issue by aryaxo** [instance01/Twitch-HLS-AdBlock#1]
doesn't seem to work anymore

**Comment by instance01** [comment]
So yesterday it stopped working for me too, but with https://github.com/instance01/Twitch-HLS-AdBlock/commit/6d96734b856a839f037d0015e0d7891f2b96d808 it seems to be fine again. I've released 0.3.0, let me know if it works for you.

**Comment by aryaxo** [comment]
you're a legend! works again.

thank you so much!!!
