### ISSUE TITLE
Alternate Player for Twitch.tv integration

### ISSUE THREAD

**Issue by BorniPL** [instance01/Twitch-HLS-AdBlock#17]
There's this extension called "Alternate Player for Twitch.tv" (https://chrome.google.com/webstore/detail/alternate-player-for-twit/bhplkbgoehhhddaoolmakpocnenplmhf). Can you possibly add the URL it uses to block ADs in there aswell?

**Comment by stoically** [comment]
You'd need to contact the Alternate Player dev to include the work-around THA uses.
