### ISSUE TITLE
Not playing when extension activated

### ISSUE THREAD

**Issue by Taquito51** [instance01/Twitch-HLS-AdBlock#18]
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

Stack Trace
lib.js:214 (getWasmBinaryVersion)

Line 214: req.open('GET', twitchBlobUrl, false);

Twitch-HLS-Ad-Block
0.6.0

Screenshot:
https://imgur.com/a/KMsRwPK

**Comment by dominic-schmid** [comment]
Same Issue here

**Comment by deklol** [comment]
Same here on Firefox :(

**Comment by hi-note** [comment]
I think the fix for this issue involves delaying everything until the player itself actually loads and before it starts loading the stream. I've noticed that when I enable it after the player loads it works.

**Comment by vohzi** [comment]
Is this extension abandoned ? No answer for a month and still not working...

**Comment by MillhioreF** [comment]
I made a fork that gets it kinda sorta working, page might need a refresh but ads should no longer play for the moment.
https://github.com/MillhioreF/Twitch-HLS-AdBlock

**Comment by deklol** [comment]
> 
> 
> I made a fork that gets it kinda sorta working, page might need a refresh but ads should no longer play for the moment.
> https://github.com/MillhioreF/Twitch-HLS-AdBlock

How do I package it to a xpi? Never done it before. I use firefox and would love to try your version.

**Comment by MillhioreF** [comment]
You're on your own there, I've never packaged an xpi myself. Google should have some tutorials for doing so.
