### ISSUE TITLE
Getting this in dev tools on Chrome.  Twitch HLS Adblock found possibly unsupported version: Current supported version: 2.9.1.

### ISSUE THREAD

**Issue by thinkpad4** [instance01/Twitch-HLS-AdBlock#22]
If that refers to the Player Core Version, they are up to 2.13.3 and are testing 2.14.0.  I don't know if this is important but there it is

**Comment by thinkpad4** [comment]
@instance01 Anything?

**Comment by thinkpad4** [comment]
Anything at all?

**Comment by MillhioreF** [comment]
The player core version used to be in the filename of the wasm worker that's being patched, but this is no longer the case so this message always appears. It's a bit deprecated and can be safely ignored, and probably should be removed honestly.

**Comment by thinkpad4** [comment]
Ok, thanks @MillhioreF
