### ISSUE TITLE
Doesn't seem to be working

### ISSUE THREAD

**Issue by AEHamrick** [instance01/Twitch-HLS-AdBlock#23]
Win 10, Chrome 76.0.3809.132

Installed as indicated, extension seems to have loaded fine but I'm still getting ads before streams.  Is there a way to access logging so I can understand if anything is getting blocked/if there are errors being generated?

**Comment by Clopaper** [comment]
Works for me on Win 10, Chrome 76.0.3809.132

**Comment by AEHamrick** [comment]
@MillhioreF With your changes, so far I see no ads, but I do get some amount of black screen with spinner before a stream starts. Haven't timed it but I'd guess somewhere between 30sec -1min, is that expected?

**Comment by MillhioreF** [comment]
Unfortunately so, it seems that Twitch has stopped feeding stream data early in my admittedly limited testing - you just get a black screen for the length of time that the ad would have played instead, I've looked briefly for workarounds but haven't come up with anything yet.

**Comment by AEHamrick** [comment]
Ah, that's obnoxious, but thanks for confirming it's not just me. With that answered I think this can be closed.
